[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 9999999
via_ir = true
evm_version = "prague"

[fuzz]
runs = 10000

[profile.intense.fuzz]
runs = 100000
max_test_rejects = 999999

[rpc_endpoints]
mainnet = "wss://ethereum-rpc.publicnode.com"
sepolia = "wss://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
